name = "test-worker"
account_id = "b2068a4d683aef98e2edcf4662eb0699"
compatibility_date = "2025-08-05"
main = "src/index.js"

[env.production]
vars = { NODE_ENV = "production" }

[env.preview]
vars = { NODE_ENV = "test" }